name: CI - Build and Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubeconform
        run: |
          curl -L -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz kubeconform
          sudo mv kubeconform /usr/local/bin/

      - name: Validate Kubernetes manifests
        run: |
          kubeconform -strict -summary k8s/

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/arhavinth/devsecops-app:${{ github.sha }} \
            -t ghcr.io/arhavinth/devsecops-app:latest \
            .

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/arhavinth/devsecops-app:${{ github.sha }}
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      - name: Push Docker image
        run: |
          docker push ghcr.io/arhavinth/devsecops-app:${{ github.sha }}
          docker push ghcr.io/arhavinth/devsecops-app:latest